"""
Django settings for Backend project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-kl94b%3f(_*^mf#6%q5%vsti$g=7d*l_fp6s*bq2&bcye2$6yl"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['10.18.1.48', 'localhost', '127.0.0.1', '0.0.0.0']

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    'App',  # ++++++++++++++++++

    'corsheaders',  # ++++++++++++++++++
    'rest_framework',  # ++++++++++++++++++
    'rest_framework.authtoken',  # ++++++++++++++++++
    'drf_yasg',  # ++++++++++++++++++

    'csp'  # ++++++++++++++++++
]

MIDDLEWARE = [

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    'corsheaders.middleware.CorsMiddleware',  # ++++++++++++++++++
    # "django.middleware.csrf.CsrfViewMiddleware",                  # ------------------
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'csp.middleware.CSPMiddleware',  # ++++++++++++++++++

]

ROOT_URLCONF = "Backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Backend.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "system",  # 数据库名称
        "USER": "root",  # 数据库用户名
        "PASSWORD": "root",  # 数据库密码
        "HOST": "localhost",  # 数据库主机，如果是本地数据库，使用 'localhost' 或 '127.0.0.1'
        "PORT": "3306",  # 数据库端口，默认是 3306
        "OPTIONS": {
            "charset": "utf8mb4",  # 设置字符集
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

CSP_DEFAULT_SRC = ("'self'", '*')
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com", '*')
CSP_FONT_SRC = ("'self'", "data:", "https://fonts.gstatic.com", '*')
CSP_SCRIPT_SRC = ("'self'", "blob:", "'unsafe-inline'", '*')
CSP_WORKER_SRC = ("'self'", "blob:", '*')
CSP_IMG_SRC = ("'self'", "data:", '*')
CSP_CONNECT_SRC = ("'self'", "http://localhost:8000", '*')
CSP_OBJECT_SRC = ("'none'", '*')
CSP_MEDIA_SRC = ("'self'", '*')
CSP_FRAME_SRC = ("'self'", "http://127.0.0.1:7860", '*')
CSP_FRAME_ANCESTORS = ("'self'", "http://127.0.0.1:5173", "http://localhost:8000", '*')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        # ...
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    # ...
}

# 沙箱支付-支付宝沙箱环境参数 ===============================================================

ALIPAY_CONFIG = {
    "APPID": "9021000143683297",
    "APP_PRIVATE_KEY": """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCgqr4O/XUgrfgR
xpBBD9KFA/HEZdf48MCBsz7gCigqzdc6qUq914/s+Rf6iugHHxuSqXrex7S1fqOu
fU+F2fsJQkTfdLTkO9NWdPVRit0s2zbkaWxgZmARWTVBU8nR6bo8j1nEjE7xV+ZF
/zc6QwKNBhS72LXSXkY9xFkflCv1DGzg22KP6fBt7HXM/4pBTb9vBZPcM+RuZ5t4
KTdy2cP98OL86WridR933wPOR7I8v/YFFsMKFcq3QWyp8iKTCHc1pNKBMnM8eWF+
P7JKjnr39w+mcy3NVnYMIH/sIklL4vuqBXLOvmO12YS2auZJdQEirSEjcDraSSNW
92VgctVfAgMBAAECggEAF0quvePpldYSnJpsHDqBJZkSSgtiTsEG2hFUX/dTpmJB
PaGq57BMjv6iMXHvZuTlbZLAm3OufhHrWbw/NI41cedXrmCwFAGbnDDdcDemORQD
Nllq2uN3MYdSDJ6V0fwabHVy/pGWpNno1KSbQDN/DFcMLMVNv+m8hholD3UUFZ8/
QUDg1pIcF0vGpWeAO/3/qm2IM9BAS7hQT04YxQxvuyvjjG42lMT5F9iOjvrPESFl
cwtwSVmsf7Im22riNAXnMoxNpQeFwD2B47Wa9Pb55SlbkwxRMqGAv8oCDZNckKTe
t9YuzSDRA316U28U80rya4HKqasxgpavSA/4rXsXlQKBgQDf9xVNQLqipQlCPL2G
KiMU7/bbWea/tOocOGpgeLQMtq45nY49gMCSL75irbofllVwruSouXCySozypoFu
hlwiLeOXerbMQMlA7yJd5KvPRcWeh58q62XaAy7Zoaai9Poc/0FwHFx/KjjNRb/7
SDw5y8xJi+aJOt+xGiMJNM/YSwKBgQC3pd+NgynA2M+kEm8omeXFuMON2/UlqNE6
VX4bWutT2lYjDVCmg24TkSq1m97TAoUE5DZegCQa0TgiCmYn1Ijt8KUbtxpfjcks
bnPveBatpn3/75wm8gQiaAMwxuv9Gi1nVL8Uk06gs/8C1aj2jdiWl7TuQhzToz3o
F8hF8lSyvQKBgFjqvM9N6osWIKXmfYwdgI4YcxZFDAKCbgvELh+c7Ea75FHFhqpO
SqX/RIPi2ykdQ1CYbvm5nc97H5hamLprp3p+Y4RJWPegpQYdqrRCTB/fYIT+7Sda
C7bRWrFWp1S9E+udP7ql1+c4uRJuJbk6xYZgrftpCp7i+9pROSW3jOkfAoGBAKZe
m55Mo8ez4q/Fj3Qdr32mu2nJSVW7kQgiqSLJBAWr93q7tkOTL2aEjUeHFJ7eWnkq
8WI8/fhZb1vPRepxbTb5Weo4v6iu/v/EdD0N8qWP/fedLz5M45fz2GgY3XMmgtlo
ec5/AK0vQydjPjVWHU+X0e5CcHD+Irgey20qcraVAoGAGt4J1zTboVeKBbe5x77E
BDDN0uwINmRWj3uMgxwtEBh395GagbLtvcRUoE8GoKdYawXyp5E1O5hYV3vlxfbB
bkwPnRF7TYs6cUxS9hgfRgqbFBPktEklbLOJiLCMYwfyMOpjL3ABlMXlnBUyaCTp
5LAMqy4tJ9FOeUZO9thlt3U=
-----END PRIVATE KEY-----
""",
    "ALIPAY_PUBLIC_KEY": """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoKq+Dv11IK34EcaQQQ/S
hQPxxGXX+PDAgbM+4AooKs3XOqlKvdeP7PkX+oroBx8bkql63se0tX6jrn1Phdn7
CUJE33S05DvTVnT1UYrdLNs25GlsYGZgEVk1QVPJ0em6PI9ZxIxO8VfmRf83OkMC
jQYUu9i10l5GPcRZH5Qr9Qxs4Ntij+nwbex1zP+KQU2/bwWT3DPkbmebeCk3ctnD
/fDi/Olq4nUfd98DzkeyPL/2BRbDChXKt0FsqfIikwh3NaTSgTJzPHlhfj+ySo56
9/cPpnMtzVZ2DCB/7CJJS+L7qgVyzr5jtdmEtmrmSXUBIq0hI3A62kkjVvdlYHLV
XwIDAQAB
-----END PUBLIC KEY-----
""",
    "NOTIFY_URL": "https://127.0.0.1:8000/payment/notify/",  # 异步通知 URL
    "RETURN_URL": "http://localhost:8080/#/main_dish_detail",  # 同步返回 URL
    "GATEWAY": "https://openapi-sandbox.dl.alipaydev.com/gateway.do"  # 沙箱环境
}
