# Generated by Django 5.1.4 on 2025-03-04 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='描述')),
                ('address', models.TextField(blank=True, default='', null=True, verbose_name='地址')),
                ('contact_person', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='联系电话')),
                ('grade', models.IntegerField(blank=True, default=0, null=True, verbose_name='卫生等级')),
                ('status', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='营业状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '食堂',
                'verbose_name_plural': '食堂',
                'db_table': 'Canteen',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='描述')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='价格')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='图片')),
                ('stock_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='库存数量')),
                ('score', models.IntegerField(blank=True, default=0, null=True, verbose_name='评分')),
                ('time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='上架时间')),
            ],
            options={
                'verbose_name': '菜品',
                'verbose_name_plural': '菜品',
                'db_table': 'Dish',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=255, null=True, unique=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='密码')),
                ('student_id', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='学号')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='性别')),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', verbose_name='头像')),
                ('phone', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='手机号')),
                ('email', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='邮箱')),
                ('dept', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='所属部门')),
                ('notes', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='角色描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='swiper/images/', verbose_name='图片')),
                ('location', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='标题位置')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'Swiper',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='反馈主题')),
                ('message', models.TextField(blank=True, default='', null=True, verbose_name='反馈信息')),
                ('resolved', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='是否已解决')),
                ('image', models.ImageField(blank=True, null=True, upload_to='feedback/images/', verbose_name='配图')),
                ('video', models.FileField(blank=True, null=True, upload_to='feedback/videos/', verbose_name='视频')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='反馈时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='App.profile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '系统反馈',
                'verbose_name_plural': '系统反馈',
                'db_table': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='DishOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='购买数量')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='总价')),
                ('status', models.CharField(blank=True, default='未支付', max_length=50, null=True, verbose_name='订单状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='下单时间')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishorders', to='App.dish', verbose_name='菜品')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishorders', to='App.profile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'DishOrder',
            },
        ),
        migrations.CreateModel(
            name='DishLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='点赞时间')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishlikes', to='App.dish', verbose_name='菜品')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishlikes', to='App.profile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'db_table': 'DishLike',
            },
        ),
        migrations.CreateModel(
            name='DishFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='收藏时间')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishfavorites', to='App.dish', verbose_name='菜品')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishfavorites', to='App.profile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'DishFavorite',
            },
        ),
        migrations.CreateModel(
            name='DishComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, default=0, null=True, verbose_name='评分')),
                ('content', models.TextField(blank=True, null=True, verbose_name='评论内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='配图')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='评论时间')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishcomments', to='App.dish', verbose_name='花卉')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishcomments', to='App.profile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'DishComment',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, default='', null=True, verbose_name='地址')),
                ('phone', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='联系电话')),
                ('is_default', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='默认地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_addresss', to='App.profile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '地址',
                'verbose_name_plural': '地址',
                'db_table': 'Address',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='App.role', verbose_name='角色'),
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='描述')),
                ('business_hours', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='营业时间')),
                ('contact_person', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='联系电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('canteen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canteen_windows', to='App.canteen', verbose_name='食堂')),
            ],
            options={
                'verbose_name': '窗口',
                'verbose_name_plural': '窗口',
                'db_table': 'Window',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='window_dishs', to='App.window', verbose_name='窗口'),
        ),
    ]
